version: "3.7"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: btc_wallet
    ports:
      - "5432:5432"

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@pg.cc
      PGADMIN_DEFAULT_PASSWORD: pg
    ports:
      - "5433:80"
